# Generated by Django 6.0.5 on 2026-05-21 15:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('unpaid', '미납'), ('paid', '납부 완료'), ('pending', '확인 대기')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penaltysettlement',
            name='exemption_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penaltysettlement',
            name='is_exempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='penaltysettlement',
            name='settled_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penaltysettlement',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='settlement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='penalties.penaltysettlement'),
        ),
        migrations.AlterField(
            model_name='penaltysettlement',
            name='reason',
            field=models.CharField(default='정산', max_length=50),
        ),
    ]
