# Generated by Django 6.0.5 on 2026-05-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='target_table',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
