# Generated by Django 6.0.5 on 2026-05-21 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
        ('objections', '0001_initial'),
        ('penalties', '0002_payment_confirmed_at_payment_confirmed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='objection',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendances.attendance'),
        ),
        migrations.AddField(
            model_name='objection',
            name='review_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objection',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objection',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_objections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objection',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='penalties.penaltysettlement'),
        ),
    ]
