# Generated by Django 6.0.5 on 2026-05-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymember',
            name='left_at',
        ),
        migrations.AddField(
            model_name='studymember',
            name='role',
            field=models.CharField(choices=[('leader', '팀장'), ('member', '팀원')], default='member', max_length=10),
        ),
    ]
